import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "@/Context/AuthContext";
import { ProfileProvider } from "@/Context/ProfileContext";
import ReduxProvider from "@/redux/provider";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import AuthInitializer from "../../components/AuthInitializer";
import GlobalUI from "../../components/GlobalUI";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NavPrana Organics",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <ProfileProvider>
              {/* <GlobalUI /> */}
              <Header />
              <AuthInitializer />

              {children}

              {/* 🔔 Global Toast Notifications */}
              <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop
                closeOnClick
                pauseOnHover
                draggable
                theme="light"
              />
              <Footer />
            </ProfileProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
